---
# ipcluster
apiVersion: v1
kind: Service
metadata:
  name: my-proxy
spec:
  selector:
    app.kubernetes.io/name: nginx-proxy # pods will be selected based on this selector
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 9376

---
# nodeport
apiVersion: v1
kind: Service
metadata:
  name: my-proxy
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx-proxy
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 9376

---
# load balancer
apiVersion: v1
kind: Service
metadata:
  name: my-proxy
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nginx-proxy
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 9376
